language: objective-c
osx_image: xcode8.2
xcode_workspace: xikolo-ios.xcworkspace
xcode_scheme: xikolo-ios

env:
  - SCHEME="openHPI-iOS" SDK="iphonesimulator"
  - SCHEME="openHPI-tvOS" SDK="appletvsimulator"
  - SCHEME="openSAP-iOS" SDK="iphonesimulator"
  - SCHEME="openSAP-tvOS" SDK="appletvsimulator"

before_install:
  - pod repo update

script:
  - xctool -workspace $TRAVIS_XCODE_WORKSPACE -scheme $SCHEME -sdk $SDK build
